# Generated by Django 4.0 on 2021-12-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=122)),
                ('dname', models.CharField(max_length=122)),
                ('dsis', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=3)),
                ('bgroup', models.CharField(max_length=122)),
            ],
        ),
    ]
