# Generated by Django 4.0 on 2021-12-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.CharField(max_length=122),
        ),
    ]
