# Generated by Django 4.0 on 2021-12-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_alter_data_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='sex',
        ),
    ]
