# Generated by Django 4.0 on 2021-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0004_remove_data_email_alter_data_age_alter_data_bgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='age',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='data',
            name='bgroup',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='data',
            name='dsis',
            field=models.CharField(max_length=122),
        ),
    ]
