# Generated by Django 4.0 on 2022-01-07 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0005_alter_data_age_alter_data_bgroup_alter_data_dsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='bgroup',
            new_name='blood_group',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='dname',
            new_name='disease',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='dsis',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='data',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='sex',
            field=models.CharField(default=django.utils.timezone.now, max_length=122),
            preserve_default=False,
        ),
    ]
